spring:
  application:
    name: Mental Health App
  data:
    mongodb:
      uri: mongodb://localhost:27017/mentaldb
      auto-index-creation: true
      port: 27018
      uuid-representation: standard
server:
  port: 9090

mental-health:
  login:
    username: ${USERNAME}
    password: ${PASSWORD}
  location-base-url: http://ip-api.com/json/

springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html